### PR TITLE
Update CYW43455 fw to 7.45.234

### PR DESCRIPTION
**Pull request by pinkforest**
Undergoing validation tests. Seems we got one freeze already but might be red herring.

**Bumping up to 7.45.234 Official Cypress firmware**

dmesg changes brcmf_c_preinit_dcmds using brcm/brcmfmac43455-sdio for chip BCM4345/6
```
Jan  4 2021 19:56:29 version 7.45.229 (617f1f5 CY) FWID 01-2dbd9d2e
Apr 15 2021 03:03:20 version 7.45.234 (4ca95bb CY) FWID 01-996384e2
```

**Affected**
- #18 
- https://github.com/iiab/iiab/issues/823#issuecomment-662285202

**Taken from Cypress - v5.10.9-2021_1020 FMAC**
- https://community.infineon.com/t5/Wi-Fi-Bluetooth-for-Linux/Cypress-Linux-WiFi-Driver-Release-FMAC-2021-10-20/td-p/322639 leading to
- https://community.infineon.com/gfawx74859/attachments/gfawx74859/WiFiBluetoothLinux/2155/1/cypress-fmac-v5.10.9-2021_1020.zip
- cyfmac43455-sdio.bin -> /lib/firmware/brcm/brcmfmac43455-sdio.bin
- cyfmac43455-sdio.clm_blob -> /lib/firmware/brcm/brcmfmac43455-sdio.clm_blob

### CODE REVIEW

**Comment by pinkforest** [comment]
@pelwell one for you I guess :)

**Comment by pinkforest** [comment]
Cypress also has the below .patches against 5.10.9 stable as part of 5.10.9-2021_1020 Package.

* SDIO (001, 006, 011, 039-041, 059, 061, 080)
* SoftAP (002, 042-043, 060, 064, 071, 078)
* Generic fixes (003, 014, 017, 045, 050-051, 053-055, 067-068, 070, 072-075)
* Wake on Wireless LAN (005, 012)
* Power saving (007, 010, 015, 077)
* USB (008-009, 030)
* Thermal throttling (013)
* 43570 (016)
* 54591 (018, 032, 057)
* RSDB (019, 021, 065-066)
* PCIE (020, 052, 076)
* Manufacturing (022, 023, 056, 081)
* Roaming (024-029)
* P2P (0031, 062, 069)
* 43012 (033-035)
* 4373 (036, 038)
* Throughput enhancement (037)
* ARP Offload (044)
* DPP (046, 058)
* Firmware/nvram (047, 063)
* Data path (048)
* Event handling (049)
* WPA3 (079)

Probably need  to check not missing anything crucial @ drivers/net/wireless/broadcom/brcm80211/brcmfmac ?

**Comment by pelwell** [comment]
I have a Pi-tailored .234 and a new CLM blob to test. It will probably be merged this week.

**Comment by pinkforest** [comment]
> I have a Pi-tailored .234 and a new CLM blob to test. It will probably be merged this week.

Could you give it out to test? I have few guinea pigs who are getting freezes with various APs and setups. I guessed there might be some special version.. confusingly Cypress had put raspberrypi tag on their release so reasonable naive consumer ought to think it was compatible :)

**Comment by pelwell** [comment]
There's a trial release here: https://drive.google.com/file/d/1kO1B8o_I2xnCfU8fUHv1VkBw--Jx6Aia/view?usp=sharing
It's actually 7.45.241, which is only two weeks old.

**Comment by pelwell** [comment]
7.45.241 firmware has been pushed to the `bullseye` branch (https://github.com/RPi-Distro/firmware-nonfree/tree/bullseye/debian/config/brcm80211/cypress, with symlinks from .../brcm).

**Comment by pinkforest** [comment]
@pelwell is there going to be AP+STA optimised firmware or is this the one that rules all?

**Comment by pelwell** [comment]
I haven't thought of a nice way to distribute the minimal firmware so that users can opt in, but since it is primarily aimed at distributions such as Internet in a Box it may just end up in the same directory as the regular firmware but with a different name. In the meantime, you can down it here: https://drive.google.com/file/d/19lAnkfe1xLrs0b0npmhwNcxcBl9kxnKJ/view?usp=sharing

**Comment by sk8board** [comment]
@pelwell 

This pull request is titled, Update CYW43455 fw to 7.45.234. Why did you push 7.45.231?

There are many reports that 7.45.231 does not support WPA3-SAE WiFi but 7.45.234 does support. How do we get 7.45.234 for WPA3-SAE?

https://github.com/RPi-Distro/firmware-nonfree/issues/41

https://github.com/raspberrypi/linux/issues/4718

**Pull request closed without merging**
